/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_juanlopez;

/**
 *
 * @author jjlm1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp_trees = new javax.swing.JPopupMenu();
        jmi_load = new javax.swing.JMenuItem();
        jmi_refrescar = new javax.swing.JMenuItem();
        pp_table = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jmb_menus = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jmi_newfile = new javax.swing.JMenuItem();
        jmi_import = new javax.swing.JMenuItem();
        jm_window = new javax.swing.JMenu();
        jmi_clearline = new javax.swing.JMenuItem();
        jmi_clear = new javax.swing.JMenuItem();
        jmi_refresh = new javax.swing.JMenuItem();
        jm_help = new javax.swing.JMenu();
        jmi_structure = new javax.swing.JMenuItem();
        jmi_comandos = new javax.swing.JMenuItem();

        jmi_load.setText("jMenuItem1");
        pp_trees.add(jmi_load);

        jmi_refrescar.setText("jMenuItem2");
        pp_trees.add(jmi_refrescar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 40));

        jButton1.setText("ENTER");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 160, 40));

        jTree1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Archivos CSV");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 300));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoría", "Precio", "Aisle", "Bin"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 500, 300));

        jm_file.setText("File");

        jmi_newfile.setText("New File");
        jm_file.add(jmi_newfile);

        jmi_import.setText("Import File");
        jm_file.add(jmi_import);

        jmb_menus.add(jm_file);

        jm_window.setText("Window");

        jmi_clearline.setText("Clear Command Line");
        jm_window.add(jmi_clearline);

        jmi_clear.setText("Clear Table");
        jm_window.add(jmi_clear);

        jmi_refresh.setText("Refresh Trees");
        jm_window.add(jmi_refresh);

        jmb_menus.add(jm_window);

        jm_help.setText("Help");

        jmi_structure.setText("Product Structure");
        jm_help.add(jmi_structure);

        jmi_comandos.setText("Comandos");
        jm_help.add(jmi_comandos);

        jmb_menus.add(jm_help);

        setJMenuBar(jmb_menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenu jm_help;
    private javax.swing.JMenu jm_window;
    private javax.swing.JMenuBar jmb_menus;
    private javax.swing.JMenuItem jmi_clear;
    private javax.swing.JMenuItem jmi_clearline;
    private javax.swing.JMenuItem jmi_comandos;
    private javax.swing.JMenuItem jmi_import;
    private javax.swing.JMenuItem jmi_load;
    private javax.swing.JMenuItem jmi_newfile;
    private javax.swing.JMenuItem jmi_refrescar;
    private javax.swing.JMenuItem jmi_refresh;
    private javax.swing.JMenuItem jmi_structure;
    private javax.swing.JPopupMenu pp_table;
    private javax.swing.JPopupMenu pp_trees;
    // End of variables declaration//GEN-END:variables
}
